num = int(input(' Digite um número : '))
print('> Tabuada do {} <'.format(num))
print('{:4} x {:2} = {}'.format(num, 1, num*1))
print('{:4} x {:2} = {}'.format(num, 2, num*2))
print('{:4} x {:2} = {}'.format(num, 3, num*3))
print('{:4} x {:2} = {}'.format(num, 4, num*4))
print('{:4} x {:2} = {}'.format(num, 5, num*5))
print('{:4} x {:2} = {}'.format(num, 6, num*6))
print('{:4} x {:2} = {}'.format(num, 7, num*7))
print('{:4} x {:2} = {}'.format(num, 8, num*8))
print('{:4} x {:2} = {}'.format(num, 9, num*9))
print('{:4} x {:2} = {}'.format(num, 10, num*10))
print('> Fim da Tabuada <')
