var = input('Digite algo : ')
print('Você escreveu algo do tipo primitivo :',type(var))
print('O que foi escrito é letra ou número ou os dois? ',var.isalnum())
print('O que foi escrito é somentenúmero? ',var.isnumeric())
print('O que foi escrito é somente letra? ',var.isalpha())
print('O que foi escrito é número decimal? ',var.isdecimal())
print('O que foi escrito tem espaço? ',var.isspace())
print('O que foi escrito somente tem letras minúsculas? ',var.islower())
print('O que foi escrito somente tem letras maiusculas? ',var.isupper())
